layout_spectrum: 0.3255319
typography_spectrum: 0.312766
color:
  lightness: 0.108634
  brandStrength: 0.8025154
  saturation: 0.2109948
  rhythmicContrast: 0.2231078
  brandColors:
    - '#262729'
    - '#C7AA88'
    - '#FFE9BD'
    - '#FFFFFF'
    - '#773930'
name: Jeroen
